In [7]:
import numpy as np

x = np.array([[11,12,13,14,15],[16,17,18,19,20],
            [21,22,23,24,25],[26,27,28,29,30]])
print(x)
print("================")
y_1 = np.amin(x)
print(y_1)
y_2 = np.amin(x,axis = 0)
print(y_2)
y_3 = np.amin(x,axis = 1)
print(y_3)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
11
[11 12 13 14 15]
[11 16 21 26]


In [8]:
import numpy as np

x = np.array([[11,12,13,14,15],[16,17,18,19,20],
            [21,22,23,24,25],[26,27,28,29,30]])
print(x)
print("================")
y_1 = np.amax(x)
print(y_1)
y_2 = np.amax(x,axis = 0)
print(y_2)
y_3 = np.amax(x,axis = 1)
print(y_3)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
30
[26 27 28 29 30]
[15 20 25 30]


In [12]:
import numpy as np

np.random.seed(20201127)
x = np.random.randint(0,50,size = [5,5])
print(x)
print("=====================")
print(np.amax(x))
print(np.amin(x))
print("=====================")
y_1 = np.ptp(x)
print(y_1)
y_2 = np.ptp(x,axis = 0)
print(y_2)
y_3 = np.ptp(x,axis = 1)
print(y_3)


[[15 13 26  2 34]
 [48 25  5 37 45]
 [10 48  1 31 25]
 [37 12 32 23 49]
 [40 31  7 46 34]]
49
1
48
[38 36 31 44 24]
[32 43 47 37 39]


In [13]:
import numpy as np 
 
a = np.array([[10, 7, 4], [3, 2, 1]])
print ('我们的数组是：')
print (a)
 
print ('调用 percentile() 函数：')
# 50% 的分位数，就是 a 里排序之后的中位数
print (np.percentile(a, 50)) 
 
# axis 为 0，在纵列上求
print (np.percentile(a, 50, axis=0)) 
 
# axis 为 1，在横行上求
print (np.percentile(a, 50, axis=1)) 
 
# 保持维度不变
print (np.percentile(a, 50, axis=1, keepdims=True))

我们的数组是：
[[10  7  4]
 [ 3  2  1]]
调用 percentile() 函数：
3.5
[6.5 4.5 2.5]
[7. 2.]
[[7.]
 [2.]]


In [15]:
import numpy as np

np.random.seed(20201127)
x = np.random.randint(0,50,size = [4,5])
print(x)
print("==============")
y_1 = np.percentile(x,[25,50])
print(y_1)
y_2 = np.percentile(x,[25,50],axis = 0)
print(y_2)
y_3 = np.percentile(x,[25,50],axis = 1)
print(y_3)

[[15 13 26  2 34]
 [48 25  5 37 45]
 [10 48  1 31 25]
 [37 12 32 23 49]]
[12.75 25.5 ]
[[13.75 12.75  4.   17.75 31.75]
 [26.   19.   15.5  27.   39.5 ]]
[[13. 25. 10. 23.]
 [15. 37. 25. 32.]]


In [16]:
import numpy as np

np.random.seed(20201127)
x = np.random.randint(0,50,size = [4,5])
print(x)
print("===================")
y_1 = np.median(x)
print(y_1)
y_2 = np.median(x,axis = 0)
print(y_2)
y_3 = np.median(x,axis = 1)
print(y_3)


[[15 13 26  2 34]
 [48 25  5 37 45]
 [10 48  1 31 25]
 [37 12 32 23 49]]
25.5
[26.  19.  15.5 27.  39.5]
[15. 37. 25. 32.]


In [17]:
import numpy as np

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(x)
print("================")
y_1 = np.mean(x)
print(y_1)  

y_2 = np.mean(x, axis=0)
print(y_2)  

y_3 = np.mean(x, axis=1)
print(y_3)  

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
23.0
[21. 22. 23. 24. 25.]
[13. 18. 23. 28. 33.]


In [19]:
import numpy as np

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(x)
print("====================")
y = np.average(x)
print(y)
y = np.average(x, axis=0)
print(y)  
y = np.average(x, axis=1)
print(y)  
print("================")

y = np.arange(1, 26).reshape([5, 5])
print(y)

z = np.average(x, weights=y)
print(z) 
z = np.average(x, axis=0, weights=y)
print(z)
z = np.average(x, axis=1, weights=y)
print(z)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
23.0
[21. 22. 23. 24. 25.]
[13. 18. 23. 28. 33.]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
27.0
[25.54545455 26.16666667 26.84615385 27.57142857 28.33333333]
[13.66666667 18.25       23.15384615 28.11111111 33.08695652]


In [20]:
import numpy as np

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(x)
print("==============")
y = np.var(x)
print(y)  
y = np.mean((x - np.mean(x)) ** 2)
print(y)  
print("==============")
y = np.var(x, ddof=1)
print(y)  
y = np.sum((x - np.mean(x)) ** 2) / (x.size - 1)
print(y) 
print("==============")
y = np.var(x, axis=0)
print(y)  
y = np.var(x, axis=1)
print(y) 

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
52.0
52.0
54.166666666666664
54.166666666666664
[50. 50. 50. 50. 50.]
[2. 2. 2. 2. 2.]


In [21]:
import numpy as np

x = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35]])
print(x)
print("==================")
y = np.std(x)
print(y)  
y = np.sqrt(np.var(x))
print(y)  
print("=================")
y = np.std(x, axis=0)
print(y)
y = np.std(x, axis=1)
print(y)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
7.211102550927978
7.211102550927978
[7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
[1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]


In [22]:
import numpy as np

x = [1, 2, 3, 4, 6]
y = [0, 2, 5, 6, 7]
print(np.cov(x))     #样本方差
print(np.cov(y))     #样本方差
print(np.cov(x, y))

print(np.var(x))     #方差
print(np.var(x, ddof=1))    #样本方差
print(np.var(y))  # 6.8    #方差
print(np.var(y, ddof=1))      #样本方差

z = np.mean((x - np.mean(x)) * (y - np.mean(y)))    #协方差
print(z)  

z = np.sum((x - np.mean(x)) * (y - np.mean(y))) / (len(x) - 1)   #样本协方差
print(z)  

z = np.dot(x - np.mean(x), y - np.mean(y)) / (len(x) - 1)     #样本协方差     
print(z)  

3.7
8.5
[[3.7  5.25]
 [5.25 8.5 ]]
2.96
3.7
6.8
8.5
4.2
5.25
5.25


In [23]:
import numpy as np

np.random.seed(20200623)
x, y = np.random.randint(0, 20, size=(2, 4))

print(x)  # [10  2  1  1]
print(y)  # [16 18 11 10]

z = np.corrcoef(x, y)
print(z)
# [[1.         0.48510096]
#  [0.48510096 1.        ]]

a = np.dot(x - np.mean(x), y - np.mean(y))
b = np.sqrt(np.dot(x - np.mean(x), x - np.mean(x)))
c = np.sqrt(np.dot(y - np.mean(y), y - np.mean(y)))
print(a / (b * c))  # 0.4851009629263671

[10  2  1  1]
[16 18 11 10]
[[1.         0.48510096]
 [0.48510096 1.        ]]
0.4851009629263671


In [24]:
import numpy as np

x = np.array([0.2, 6.4, 3.0, 1.6])
bins = np.array([0.0, 1.0, 2.5, 4.0, 10.0])
inds = np.digitize(x, bins)
print(inds)  # [1 4 3 2]
for n in range(x.size):
    print(bins[inds[n] - 1], "<=", x[n], "<", bins[inds[n]])

# 0.0 <= 0.2 < 1.0
# 4.0 <= 6.4 < 10.0
# 2.5 <= 3.0 < 4.0
# 1.0 <= 1.6 < 2.5

[1 4 3 2]
0.0 <= 0.2 < 1.0
4.0 <= 6.4 < 10.0
2.5 <= 3.0 < 4.0
1.0 <= 1.6 < 2.5


In [25]:
import numpy as np

x = np.array([1.2, 10.0, 12.4, 15.5, 20.])
bins = np.array([0, 5, 10, 15, 20])
inds = np.digitize(x, bins, right=True)
print(inds)  # [1 2 3 4 4]

inds = np.digitize(x, bins, right=False)
print(inds)  # [1 3 3 4 5]

[1 2 3 4 4]
[1 3 3 4 5]


In [27]:
#练习题
#1.

from numpy.linalg import inv 
from numpy import dot, transpose 
X = [[1, 6, 2] , [1, 8, 1] , [1, 10, 0] , [1 , 14, 2] , [1, 18, 0]] 
y = [[7] , [9] , [13] , [17.5] , [18]]

print(X)
print(y)
print("=====================")
print(dot(inv(dot(transpose(X) , X)) , dot(transpose(X) , y)))

#另一种解法
print("另一种解法：")
from numpy.linalg import lstsq
print(lstsq(X,y)[0])

[[1, 6, 2], [1, 8, 1], [1, 10, 0], [1, 14, 2], [1, 18, 0]]
[[7], [9], [13], [17.5], [18]]
[[1.1875    ]
 [1.01041667]
 [0.39583333]]
另一种解法：
[[1.1875    ]
 [1.01041667]
 [0.39583333]]


E:\Anaconda\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


In [30]:
#2.
import numpy as np

a = np.random.randint(1, 10, [5, 3])
print(a)
print("==============")
answer = np.amax(a,axis = 1)
print(answer)

[[4 1 7]
 [9 8 9]
 [2 1 9]
 [2 1 8]
 [5 6 2]]
[7 9 9 8 6]


In [34]:
#3.
import numpy as np

A=np.array([[3,7,5],
[8,4,3],
[2,4,9]])
print(A)
print("=============")
answer = np.ptp(A)
print(answer)

[[3 7 5]
 [8 4 3]
 [2 4 9]]
7


In [36]:
#4.
import numpy as np

S = [9.7, 10, 10.3, 9.7,10,10.3,9.7,10,10.3]
print(S)
#均值
value_mean = np.mean(S)
print("均值：" + str(value_mean))
#方差
value_var = np.var(S)
print("方差：" + str(value_var))
#标准差
value_std = np.std(S)
print("标准差：" + str(value_std))
#协方差


[9.7, 10, 10.3, 9.7, 10, 10.3, 9.7, 10, 10.3]
均值：10.0
方差：0.06000000000000029
标准差：0.2449489742783184
