In [1]:
import numpy as np

In [3]:
help(np.save)

Help on function save in module numpy:

save(file, arr, allow_pickle=True, fix_imports=True)
    Save an array to a binary file in NumPy ``.npy`` format.
    
    Parameters
    ----------
    file : file, str, or pathlib.Path
        File or filename to which the data is saved.  If file is a file-object,
        then the filename is unchanged.  If file is a string or Path, a ``.npy``
        extension will be appended to the filename if it does not already
        have one.
    arr : array_like
        Array data to be saved.
    allow_pickle : bool, optional
        Allow saving object arrays using Python pickles. Reasons for disallowing
        pickles include security (loading pickled data can execute arbitrary
        code) and portability (pickled objects may not be loadable on different
        Python installations, for example if the stored objects require libraries
        that are not available, and not all pickled data is compatible between
        Python 2 and Python 3).
  

In [4]:
import numpy as np

testfile1 = r'testfile1.npy'
np.random.seed(20201123)
x = np.random.uniform(1,2,[3,4])
print(x)
np.save(testfile1,x)
y = np.load(testfile1)
print(y)

[[1.03911501 1.91357784 1.21820335 1.61869406]
 [1.25371066 1.75731372 1.16270282 1.77498589]
 [1.41520052 1.15138986 1.34765902 1.22682386]]
[[1.03911501 1.91357784 1.21820335 1.61869406]
 [1.25371066 1.75731372 1.16270282 1.77498589]
 [1.41520052 1.15138986 1.34765902 1.22682386]]


In [11]:
import numpy as np

testfile2 = r'testfile2.npz'
x = np.linspace(0,np.pi,5)
print(x)
y = np.sin(x)
z = np.cos(x)
print(y)
print(z)
np.savez(testfile2,x,y,d_z = z)
testdata = np.load(testfile2)
print("=====================================")
print(testdata)
print(testdata.files)
print(testdata['arr_0'],testdata['arr_1'],testdata['d_z'])

[0.         0.78539816 1.57079633 2.35619449 3.14159265]
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
['d_z', 'arr_0', 'arr_1']
[0.         0.78539816 1.57079633 2.35619449 3.14159265] [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16] [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


In [13]:
import numpy as np

testfile3 = r'testfile3'
x = np.arange(0,10).reshape(2,-1)
print(x)
np.savetxt(testfile3,x)
y = np.loadtxt(testfile3)
print(y)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [17]:
import numpy as np

testfile4 = r'testfile4.csv'
x = np.arange(0,20,2).reshape(5,-1)
print(x)
np.savetxt(testfile4,x,fmt = '%.2f')
y = np.loadtxt(testfile4)
print(y)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]]
[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]
 [12. 14.]
 [16. 18.]]


In [21]:
import numpy as np

testfile5 = r'testfile5.csv'
x = np.loadtxt(testfile5,delimiter = ',',skiprows = 1)
print(x)
y = np.loadtxt(testfile5,delimiter = ',',skiprows = 1,usecols = (1,2))
print(y)
value1,value2 = np.loadtxt(testfile5,delimiter = ',',skiprows = 1,usecols = (1,2),unpack = True)
print(value1)
print(value2)

[[  1.  123.    1.4  23. ]
 [  2.  110.    0.5  18. ]
 [  3.  164.    2.1  19. ]]
[[123.    1.4]
 [110.    0.5]
 [164.    2.1]]
[123. 110. 164.]
[1.4 0.5 2.1]


In [25]:
import numpy as np

testfile5 = r'testfile5.csv'
x = np.genfromtxt(testfile5,delimiter = ',',names = True)
print(x)
print(type(x))
print(x.dtype)
print(x['id'],x['value1'],x['value2'],x['value3'])

[(1., 123., 1.4, 23.) (2., 110., 0.5, 18.) (3., 164., 2.1, 19.)]
<class 'numpy.ndarray'>
[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')]
[1. 2. 3.] [123. 110. 164.] [1.4 0.5 2.1] [23. 18. 19.]


In [31]:
import numpy as np 

testfile6 = r'testfile6.csv'
x = np.genfromtxt(testfile6,delimiter = ',',names = True)
print(x)
print(type(x))
print(x.dtype)
print(x['id'],x['value1'],x['value2'],x['value3'])

[(1.,  2.,  3., 4.) (1., nan,  2., 3.) (1.,  2., nan, 5.)]
<class 'numpy.ndarray'>
[('id', '<f8'), ('value1', '<f8'), ('value2', '<f8'), ('value3', '<f8')]
[1. 1. 1.] [ 2. nan  2.] [ 3.  2. nan] [4. 3. 5.]


In [32]:
import numpy as np

np.set_printoptions(precision=4)
x = np.array([1.123456789])
print(x)  # [1.1235]

np.set_printoptions(threshold=20)
x = np.arange(50)
print(x)  # [ 0  1  2 ... 47 48 49]

np.set_printoptions(threshold=np.iinfo(np.int).max)
print(x)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
#  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
#  48 49]

eps = np.finfo(float).eps
x = np.arange(4.)
x = x ** 2 - (x + eps) ** 2
print(x)  
# [-4.9304e-32 -4.4409e-16  0.0000e+00  0.0000e+00]
np.set_printoptions(suppress=True)
print(x)  # [-0. -0.  0.  0.]

x = np.linspace(0, 10, 10)
print(x)
# [ 0.      1.1111  2.2222  3.3333  4.4444  5.5556  6.6667  7.7778  8.8889
#  10.    ]
np.set_printoptions(precision=2, suppress=True, threshold=5)
print(x)  # [ 0.    1.11  2.22 ...  7.78  8.89 10.  ]

[1.1235]
[ 0  1  2 ... 47 48 49]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[-4.9304e-32 -4.4409e-16  0.0000e+00  0.0000e+00]
[-0. -0.  0.  0.]
[ 0.      1.1111  2.2222  3.3333  4.4444  5.5556  6.6667  7.7778  8.8889
 10.    ]
[ 0.    1.11  2.22 ...  7.78  8.89 10.  ]


In [33]:
help(np.iinfo)

Help on class iinfo in module numpy:

class iinfo(builtins.object)
 |  iinfo(int_type)
 |  
 |  iinfo(type)
 |  
 |  Machine limits for integer types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  min : int
 |      The smallest integer expressible by the type.
 |  max : int
 |      The largest integer expressible by the type.
 |  
 |  Parameters
 |  ----------
 |  int_type : integer type, dtype, or instance
 |      The kind of integer data type to get information about.
 |  
 |  See Also
 |  --------
 |  finfo : The equivalent for floating point data types.
 |  
 |  Examples
 |  --------
 |  With types:
 |  
 |  >>> ii16 = np.iinfo(np.int16)
 |  >>> ii16.min
 |  -32768
 |  >>> ii16.max
 |  32767
 |  >>> ii32 = np.iinfo(np.int32)
 |  >>> ii32.min
 |  -2147483648
 |  >>> ii32.max
 |  2147483647
 |  
 |  With instances:
 |  
 |  >>> ii32 = np.iinfo(np.int32(10))
 |  >>> ii32.min
 |  -2147483648
 |  >>> ii32.max
 |  2147483647
 |  
 

In [34]:
help(np.finfo)

Help on class finfo in module numpy:

class finfo(builtins.object)
 |  finfo(dtype)
 |  
 |  finfo(dtype)
 |  
 |  Machine limits for floating point types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  eps : float
 |      The smallest representable positive number such that
 |      ``1.0 + eps != 1.0``.  Type of `eps` is an appropriate floating
 |      point type.
 |  epsneg : floating point number of the appropriate type
 |      The smallest representable positive number such that
 |      ``1.0 - epsneg != 1.0``.
 |  iexp : int
 |      The number of bits in the exponent portion of the floating point
 |      representation.
 |  machar : MachAr
 |      The object which calculated these parameters and holds more
 |      detailed information.
 |  machep : int
 |      The exponent that yields `eps`.
 |  max : floating point number of the appropriate type
 |      The largest representable number.
 |  maxexp : int
 |      The smallest 

In [35]:
import numpy as np

x = np.get_printoptions()
print(x)

{'edgeitems': 3, 'threshold': 5, 'floatmode': 'maxprec', 'precision': 2, 'suppress': True, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': False}


In [1]:
import numpy as np

rand_arr = np.random.random([5,3])
print(rand_arr)
np.set_printoptions(precision = 3)
print(rand_arr)

[[0.0107548  0.35954151 0.66162149]
 [0.16272273 0.57774507 0.17774303]
 [0.47837153 0.75690533 0.27104246]
 [0.01191847 0.21773997 0.97291623]
 [0.76891329 0.49534533 0.22709885]]
[[0.011 0.36  0.662]
 [0.163 0.578 0.178]
 [0.478 0.757 0.271]
 [0.012 0.218 0.973]
 [0.769 0.495 0.227]]


In [3]:
import numpy as np

a = np.arange(0,10)
print(a)
np.set_printoptions(threshold = 6)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 ... 7 8 9]


In [5]:
np.set_printoptions(threshold = )

In [7]:
import numpy as np

a = np.arange(0,10)
print(a)
np.set_printoptions(threshold = 1000)
print(a)

[0 1 2 ... 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
