In [7]:
# 导入库 读取文件
import numpy as np 
import pandas as pd 

df_csv = pd.read_csv('data/my_csv.csv') # 读取csv文件
print(df_csv)
print("===================================")
df_txt = pd.read_table('data/my_table.txt') # 读取txt文件
print(df_txt)
print("===================================")
df_excel = pd.read_excel('data/my_excel.xlsx')
print(df_excel)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7
   col1 col2  col3             col4
0     2    a   1.4   apple 2020/1/1
1     3    b   3.4  banana 2020/1/2
2     6    c   2.5  orange 2020/1/5
3     5    d   3.2   lemon 2020/1/7
   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7


In [12]:
# 设置参数
import numpy as np 
import pandas as pd 

df_txt1 = pd.read_table('data/my_table.txt',header = None)
print(df_txt1)
print("======================================")
df_csv1 = pd.read_csv('data/my_csv.csv',index_col = ['col1','col2'])
print(df_csv1)
print("======================================")
df_txt2 = pd.read_table('data/my_table.txt',usecols = ['col1','col2'])
print(df_txt2)
print("======================================")
df_csv2 = pd.read_csv('data/my_csv.csv',parse_dates = ['col5'])
print(df_csv2)
print("======================================")
df_excel1 = pd.read_excel('data/my_excel.xlsx',nrows = 2)
print(df_excel1)

      0     1     2                3
0  col1  col2  col3             col4
1     2     a   1.4   apple 2020/1/1
2     3     b   3.4  banana 2020/1/2
3     6     c   2.5  orange 2020/1/5
4     5     d   3.2   lemon 2020/1/7
           col3    col4      col5
col1 col2                        
2    a      1.4   apple  2020/1/1
3    b      3.4  banana  2020/1/2
6    c      2.5  orange  2020/1/5
5    d      3.2   lemon  2020/1/7
   col1 col2
0     2    a
1     3    b
2     6    c
3     5    d
   col1 col2  col3    col4       col5
0     2    a   1.4   apple 2020-01-01
1     3    b   3.4  banana 2020-01-02
2     6    c   2.5  orange 2020-01-05
3     5    d   3.2   lemon 2020-01-07
   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2


In [13]:
# 设置参数 sep
import numpy as np 
import pandas as pd 

df_txt = pd.read_table('data/my_table_special_sep.txt') # 不带sep参数
print(df_txt)

              col1 |||| col2
0  TS |||| This is an apple.
1    GQ |||| My name is Bob.
2         WT |||| Well done!
3    PT |||| May I help you?


In [18]:
# 使用sep 参数
import numpy as np 
import pandas as pd 

df_txt_sep =  pd.read_table('data/my_table_special_sep.txt',sep = ' \|\|\|\| ', engine = 'python') # 使用sep参数
print(df_txt_sep)

  col1               col2
0   TS  This is an apple.
1   GQ    My name is Bob.
2   WT         Well done!
3   PT    May I help you?


In [20]:
# 数据写入
import numpy as np 
import pandas as pd 

df_csv = pd.read_csv('data/my_csv.csv')
print(df_csv)
df_csv.to_csv('data/yingrushi_csv.csv',index = False)
print("=======================================")
df_excel = pd.read_excel('data/my_excel.xlsx')
print(df_excel)
df_excel.to_excel('data/yingrushi_excel.xlsx',index = False)

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7
   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7


In [23]:
# 写入txt文件
import numpy as np 
import pandas as pd 

df_txt = pd.read_table('data/my_table.txt')
print(df_txt)
df_txt.to_csv('data/yingrushi_txt.txt',sep = '\t',index = False)

   col1 col2  col3             col4
0     2    a   1.4   apple 2020/1/1
1     3    b   3.4  banana 2020/1/2
2     6    c   2.5  orange 2020/1/5
3     5    d   3.2   lemon 2020/1/7


In [31]:
# 转换为markdown和latex
import numpy as np 
import pandas as pd 
import tabulate

df_csv = pd.read_csv('data/my_csv.csv')
print(df_csv)
print("=======================")
print(df_csv.to_markdown())
print("=======================")
print(df_csv.to_latex())

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5
3     5    d   3.2   lemon  2020/1/7
|    |   col1 | col2   |   col3 | col4   | col5     |
|---:|-------:|:-------|-------:|:-------|:---------|
|  0 |      2 | a      |    1.4 | apple  | 2020/1/1 |
|  1 |      3 | b      |    3.4 | banana | 2020/1/2 |
|  2 |      6 | c      |    2.5 | orange | 2020/1/5 |
|  3 |      5 | d      |    3.2 | lemon  | 2020/1/7 |
\begin{tabular}{lrlrll}
\toprule
{} &  col1 & col2 &  col3 &    col4 &      col5 \\
\midrule
0 &     2 &    a &   1.4 &   apple &  2020/1/1 \\
1 &     3 &    b &   3.4 &  banana &  2020/1/2 \\
2 &     6 &    c &   2.5 &  orange &  2020/1/5 \\
3 &     5 &    d &   3.2 &   lemon &  2020/1/7 \\
\bottomrule
\end{tabular}



In [1]:
# Series 
import numpy as np 
import pandas as pd 

pd_series = pd.Series(data = [100,'a',{'dic1':5}],index = pd.Index(['id1',20,'third'],name = 'my_idx'),dtype = 'object',name = 'my_name')
print(pd_series)

my_idx
id1              100
20                 a
third    {'dic1': 5}
Name: my_name, dtype: object


In [2]:
import numpy as np 
import pandas as pd 

pd_series = pd.Series(data = [100,'a',{'dic1':5}],index = pd.Index(['id1',20,'third'],name = 'my_idx'),dtype = 'object',name = 'my_name')
print(pd_series)
print("=====================")
print(pd_series.values)
print(pd_series.index)
print(pd_series.dtype)
print(pd_series.name)

my_idx
id1              100
20                 a
third    {'dic1': 5}
Name: my_name, dtype: object
[100 'a' {'dic1': 5}]
Index(['id1', 20, 'third'], dtype='object', name='my_idx')
object
my_name


In [4]:
# .shape
import numpy as np 
import pandas as pd 

pd_series = pd.Series(data = [100,'a',{'dic1':5}],index = pd.Index(['id1',20,'third'],name = 'my_idx'),dtype = 'object',name = 'my_name')
print(pd_series)
print("=====================")
print(pd_series.shape)

# 索引
print(pd_series[20])

my_idx
id1              100
20                 a
third    {'dic1': 5}
Name: my_name, dtype: object
(3,)
a


In [10]:
# dataframe
import numpy as np 
import pandas as pd 

data = [[1,'a',1.2],[2,'b',2.2],[3,'c',3.2]]
df = pd.DataFrame(data = data,index = ['row_%d' % i for i in range(3)],columns = ['col_0','col_1','col_2'])
print(df)

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2


In [9]:
data = [[1, 'a', 1.2], [2, 'b', 2.2], [3, 'c', 3.2]]
df = pd.DataFrame(data = data,index = ['row_%d'%i for i in range(3)],columns=['col_0', 'col_1', 'col_2'])
print(df)

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2


In [11]:
# 构造dataframe
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data = {'col_0':[1,2,3],'col_1':list('abc'),'col2':[1.2,2.2,3.2]},index = ['row_%d' % i for i in range(3)])
print(df)

       col_0 col_1  col2
row_0      1     a   1.2
row_1      2     b   2.2
row_2      3     c   3.2


In [16]:
# 索引
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data = {'col_0':[1,2,3],'col_1':list('abc'),'col2':[1.2,2.2,3.2]},index = ['row_%d' % i for i in range(3)])
print(df)
print("===============================")
print(df['col_0'])
print("===============================")
print(df[['col_0','col_1']])
print(type(df[['col_0','col_1']]))

       col_0 col_1  col2
row_0      1     a   1.2
row_1      2     b   2.2
row_2      3     c   3.2
row_0    1
row_1    2
row_2    3
Name: col_0, dtype: int64
       col_0 col_1
row_0      1     a
row_1      2     b
row_2      3     c
<class 'pandas.core.frame.DataFrame'>


In [21]:
# 索引
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data = {'col_0':[1,2,3],'col_1':list('abc'),'col2':[1.2,2.2,3.2]},index = ['row_%d' % i for i in range(3)])
print(df)
print("===============================")
print(df.values)
print("===============================")
print(df.index)
print("===============================")
print(df.columns)
print("===============================")
print(df.dtypes)
print("===============================")
print(df.shape)

       col_0 col_1  col2
row_0      1     a   1.2
row_1      2     b   2.2
row_2      3     c   3.2
[[1 'a' 1.2]
 [2 'b' 2.2]
 [3 'c' 3.2]]
Index(['row_0', 'row_1', 'row_2'], dtype='object')
Index(['col_0', 'col_1', 'col2'], dtype='object')
col_0      int64
col_1     object
col2     float64
dtype: object
(3, 3)


In [22]:
# 转置
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data = {'col_0':[1,2,3],'col_1':list('abc'),'col2':[1.2,2.2,3.2]},index = ['row_%d' % i for i in range(3)])
print(df)
print("===============================")
print(df.T)

       col_0 col_1  col2
row_0      1     a   1.2
row_1      2     b   2.2
row_2      3     c   3.2
      row_0 row_1 row_2
col_0     1     2     3
col_1     a     b     c
col2    1.2   2.2   3.2


In [27]:
# 创建Panel
import numpy as np 
import pandas as pd 

# 创建 空Panel
p = pd.Panel()
print(p)
print("========================")

# 从 3Dndarray 创建Panel
np.random.seed(20201218)
data = np.random.rand(2,4,5)
print(data)
print("========================")
p = pd.Panel()
print(p)

<pandas.__getattr__.<locals>.Panel object at 0x0000019092A60320>
[[[0.82053113 0.40822766 0.0043119  0.59250126 0.68065678]
  [0.41462002 0.63850114 0.84972809 0.83815841 0.49665225]
  [0.69873626 0.3915328  0.96118411 0.28867098 0.16603775]
  [0.18647815 0.21783024 0.223223   0.87727195 0.5078422 ]]

 [[0.72346079 0.72471709 0.62397643 0.60783676 0.17108011]
  [0.35284973 0.95773571 0.02642248 0.66253958 0.73585733]
  [0.94741633 0.38742025 0.00119016 0.95563109 0.05178133]
  [0.05578195 0.05838634 0.04496512 0.66466131 0.92483172]]]
<pandas.__getattr__.<locals>.Panel object at 0x0000019092A608D0>


In [32]:
type(p)

pandas.__getattr__.<locals>.Panel

TypeError: Panel() takes no arguments

In [35]:
# 常用函数
import numpy as np 
import pandas as pd

df = pd.read_csv('data/learn_pandas.csv')
print(df.columns)

Index(['School', 'Grade', 'Name', 'Gender', 'Height', 'Weight', 'Transfer',
       'Test_Number', 'Test_Date', 'Time_Record'],
      dtype='object')


In [1]:
# 常用函数
import numpy as np 
import pandas as pd

df = pd.read_csv('data/learn_pandas.csv')
df = df[df.columns[:7]]
print(df)

                            School      Grade            Name  Gender  Height  \
0    Shanghai Jiao Tong University   Freshman    Gaopeng Yang  Female   158.9   
1                Peking University   Freshman  Changqiang You    Male   166.5   
2    Shanghai Jiao Tong University     Senior         Mei Sun    Male   188.9   
3                 Fudan University  Sophomore    Xiaojuan Sun  Female     NaN   
4                 Fudan University  Sophomore     Gaojuan You    Male   174.0   
..                             ...        ...             ...     ...     ...   
195               Fudan University     Junior    Xiaojuan Sun  Female   153.9   
196            Tsinghua University     Senior         Li Zhao  Female   160.9   
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua University  Sophomore     Chunpeng Lv    Male   155.7   

     Weight Transfer  
0   

In [37]:
# 1.汇总函数
import numpy as np 
import pandas as pd 

print(df.head(2))
print("========================")
print(df.tail(3))

                          School     Grade            Name  Gender  Height  \
0  Shanghai Jiao Tong University  Freshman    Gaopeng Yang  Female   158.9   
1              Peking University  Freshman  Changqiang You    Male   166.5   

   Weight Transfer  
0    46.0        N  
1    70.0        N  
                            School      Grade            Name  Gender  Height  \
197  Shanghai Jiao Tong University     Senior  Chengqiang Chu  Female   153.9   
198  Shanghai Jiao Tong University     Senior   Chengmei Shen    Male   175.3   
199            Tsinghua University  Sophomore     Chunpeng Lv    Male   155.7   

     Weight Transfer  
197    45.0        N  
198    71.0        N  
199    51.0        N  


In [38]:
# info , describe
import numpy as np 
import pandas as pd 

print(df.info())
print("========================")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   School    200 non-null    object 
 1   Grade     200 non-null    object 
 2   Name      200 non-null    object 
 3   Gender    200 non-null    object 
 4   Height    183 non-null    float64
 5   Weight    189 non-null    float64
 6   Transfer  188 non-null    object 
dtypes: float64(2), object(5)
memory usage: 11.1+ KB
None
           Height      Weight
count  183.000000  189.000000
mean   163.218033   55.015873
std      8.608879   12.824294
min    145.400000   34.000000
25%    157.150000   46.000000
50%    161.900000   51.000000
75%    167.500000   65.000000
max    193.900000   89.000000


In [2]:
# 统计函数
import numpy as np 
import pandas as pd 

df_demo = df[['Height','Weight']]
print(df_demo.mean()) # 均值
print(df_demo.max()) # 最大值
print(df_demo.min()) # 最小值


Height    163.218033
Weight     55.015873
dtype: float64
Height    193.9
Weight     89.0
dtype: float64
Height    145.4
Weight     34.0
dtype: float64


In [42]:
# quantile , count , idxmax 
import numpy as np 
import pandas as pd 

print(df_demo.quantile(0.75))
print(df_demo.count())
print(df_demo.idxmax())
print(df_demo.idxmin())

Height    167.5
Weight     65.0
Name: 0.75, dtype: float64
Height    183
Weight    189
dtype: int64
Height    193
Weight      2
dtype: int64
Height    143
Weight     49
dtype: int64


In [43]:
# axis 参数
import numpy as np 
import pandas as pd

# 只做演示，身高和体重的均值并没有意义
print(df_demo.mean(axis = 1).head()) # axis 按行聚合

0    102.45
1    118.25
2    138.95
3     41.00
4    124.00
dtype: float64


In [44]:
# 唯一值函数
import numpy as np 
import pandas as pd 

print(df['School'].unique())
print(df['School'].nunique())

['Shanghai Jiao Tong University' 'Peking University' 'Fudan University'
 'Tsinghua University']
4


In [45]:
# 唯一值函数
import numpy as np 
import pandas as pd 

print(df['School'].value_counts())

Tsinghua University              69
Shanghai Jiao Tong University    57
Fudan University                 40
Peking University                34
Name: School, dtype: int64


In [6]:
# drop_duplicates
import numpy as np 
import pandas as pd 

df_demo = df[['Gender','Transfer','Name']]
print(df_demo.drop_duplicates(['Gender','Transfer']))
print("=============================")
print(df_demo.drop_duplicates(['Gender','Transfer'],keep = 'last'))
print("=============================")
print(df_demo.drop_duplicates(['Name','Gender'],keep = False).head())
print("=============================")
print(df['School'].drop_duplicates()) # 在Series上也可以使用

    Gender Transfer            Name
0   Female        N    Gaopeng Yang
1     Male        N  Changqiang You
12  Female      NaN        Peng You
21    Male      NaN   Xiaopeng Shen
36    Male        Y    Xiaojuan Qin
43  Female        Y      Gaoli Feng
     Gender Transfer            Name
147    Male      NaN        Juan You
150    Male        Y   Chengpeng You
169  Female        Y   Chengquan Qin
194  Female      NaN     Yanmei Qian
197  Female        N  Chengqiang Chu
199    Male        N     Chunpeng Lv
   Gender Transfer            Name
0  Female        N    Gaopeng Yang
1    Male        N  Changqiang You
2    Male        N         Mei Sun
4    Male        N     Gaojuan You
5  Female        N     Xiaoli Qian
0    Shanghai Jiao Tong University
1                Peking University
3                 Fudan University
5              Tsinghua University
Name: School, dtype: object


In [9]:
# duplicates 
import numpy as np 
import pandas as pd 

print(df_demo.duplicated(['Gender','Transfer']).head())
print("=========================")
print(df['School'].duplicated().head())  # 在 Series 上也可以使用

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3    False
4     True
Name: School, dtype: bool


In [11]:
# 替换函数
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/learn_pandas.csv')
df = df[df.columns[:7]]
print(df['Gender'].replace({'Female':0,'Male':1}).head()) # 通过字典替换
print("============================")
print(df['Gender'].replace(['Female','Male'],[0,1]).head()) # 通过两个列表替换

0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64
0    0
1    1
2    1
3    0
4    1
Name: Gender, dtype: int64


In [13]:
# ffill bfill
import numpy as np 
import pandas as pd 

s = pd.Series(['a',1,'b',2,1,1,'a'])
print(s)
print("=====================")
print(s.replace([1,2],method = 'ffill'))
print("=====================")
print(s.replace([1,2],method = 'bfill'))

0    a
1    1
2    b
3    2
4    1
5    1
6    a
dtype: object
0    a
1    a
2    b
3    b
4    b
5    b
6    a
dtype: object
0    a
1    b
2    b
3    a
4    a
5    a
6    a
dtype: object


In [20]:
# 逻辑替换 where mask 
import numpy as np 
import pandas as pd 

s = pd.Series([-1,1.2345,100,-50])
print(s)
print("=====================")
print(s.where(s < 0))
print("=====================")
print(s.where(s < 0,100))
print("=====================")
print(s.mask(s < 0))
print("=====================")
print(s.mask(s < 0,-50))

0     -1.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64
0    -1.0
1     NaN
2     NaN
3   -50.0
dtype: float64
0     -1.0
1    100.0
2    100.0
3    -50.0
dtype: float64
0         NaN
1      1.2345
2    100.0000
3         NaN
dtype: float64
0    -50.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64


In [21]:
# 传入Series索引一致的布尔序列
import numpy as np 
import pandas as pd 

s = pd.Series([-1,1.2345,100,-50])
s_condition = pd.Series([True,False,False,True],index = s.index)
print(s.mask(s_condition,-50)) 

0    -50.0000
1      1.2345
2    100.0000
3    -50.0000
dtype: float64


In [24]:
# 数值替换
import numpy as np 
import pandas as pd 

s = pd.Series([-1,1.2345,100,-50]) # 按精度四舍五入
print(s.round(2))
print("======================")
print(s.abs())
print("======================")
print(s.clip(0,2)) # 前两个数分别表示上下截断边界

0     -1.00
1      1.23
2    100.00
3    -50.00
dtype: float64
0      1.0000
1      1.2345
2    100.0000
3     50.0000
dtype: float64
0    0.0000
1    1.2345
2    2.0000
3    0.0000
dtype: float64


In [26]:
# 排序函数
import numpy as np 
import pandas as pd 

df_demo = df[['Grade','Name','Height','Weight']].set_index(['Grade','Name'])
# 对身高进行排序
print(df_demo.sort_values('Height').head())
print("==========================")
print(df_demo.sort_values('Height',ascending = False).head())

                         Height  Weight
Grade     Name                         
Junior    Xiaoli Chu      145.4    34.0
Senior    Gaomei Lv       147.3    34.0
Sophomore Peng Han        147.8    34.0
Senior    Changli Lv      148.7    41.0
Sophomore Changjuan You   150.5    40.0
                        Height  Weight
Grade    Name                         
Senior   Xiaoqiang Qin   193.9    79.0
         Mei Sun         188.9    89.0
         Gaoli Zhao      186.5    83.0
Freshman Qiang Han       185.3    87.0
Senior   Qiang Zheng     183.9    87.0


In [27]:
# 多列排序
import numpy as np 
import pandas as pd 

# 体重相同的情况下，对身高进行排序，并且保持身高降序排列，体重升序排列
print(df_demo.sort_values(['Weight','Height'],ascending = [True,False]).head())

                       Height  Weight
Grade     Name                       
Sophomore Peng Han      147.8    34.0
Senior    Gaomei Lv     147.3    34.0
Junior    Xiaoli Chu    145.4    34.0
Sophomore Qiang Zhou    150.5    36.0
Freshman  Yanqiang Xu   152.4    38.0


In [28]:
# 索引排序
import numpy as np 
import pandas as pd 

print(df_demo.sort_index(level = ['Grade','Name'],ascending = [True,False]).head())

                        Height  Weight
Grade    Name                         
Freshman Yanquan Wang    163.5    55.0
         Yanqiang Xu     152.4    38.0
         Yanqiang Feng   162.3    51.0
         Yanpeng Lv        NaN    65.0
         Yanli Zhang     165.1    52.0


In [1]:
# apply函数
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/learn_pandas.csv')
df = df[df.columns[:7]]
df_demo = df[['Height','Weight']]
# 定义函数
def my_mean(x):
    return x.mean()

print(df_demo.apply(my_mean))

Height    163.218033
Weight     55.015873
dtype: float64


In [2]:
# apply 函数 lambda
import numpy as np 
import pandas as pd 

print(df_demo.apply(lambda x:x.mean()))

Height    163.218033
Weight     55.015873
dtype: float64


In [3]:
# 改变axis = 1 参数
import numpy as np 
import pandas as pd 

print(df_demo.apply(lambda x:x.mean(),axis = 1).head())

0    102.45
1    118.25
2    138.95
3     41.00
4    124.00
dtype: float64


In [5]:
# mad函数
import numpy as np 
import pandas as pd 

# 普通方法计算 mad 值
print(df_demo.apply(lambda x:(x - x.mean()).abs().mean()))

print("===================")
# 使用内置 mad 函数
print(df_demo.mad())

Height     6.707229
Weight    10.391870
dtype: float64
Height     6.707229
Weight    10.391870
dtype: float64


In [7]:
# 滑窗对象
import numpy as np 
import pandas as pd 

s = pd.Series([1,2,3,4,5])
print(s)
roller = s.rolling(window = 3)
print(roller)

0    1
1    2
2    3
3    4
4    5
dtype: int64
Rolling [window=3,center=False,axis=0]


In [9]:
# roller 
import numpy as np 
import pandas as pandas 

s = pd.Series([1,2,3,4,5])
print(s)
print("=========================")
roller = s.rolling(window = 3)
print(roller.mean()) # 均值
print("=========================")
print(roller.sum()) # 求和

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64
0     NaN
1     NaN
2     6.0
3     9.0
4    12.0
dtype: float64


In [10]:
# 滑动相关系数和滑动协方差
import numpy as np 
import pandas as pd 

s = pd.Series([1,2,3,4,5])
print(s)
print("=========================")
roller = s.rolling(window = 3)
s2 = pd.Series([1,2,6,16,30])
print(s2)
print("==========================")

print(roller.cov(s2))  # 滑动协方差
print("==========================")
print(roller.corr(s2))  # 滑动相关系数

0    1
1    2
2    3
3    4
4    5
dtype: int64
0     1
1     2
2     6
3    16
4    30
dtype: int64
0     NaN
1     NaN
2     2.5
3     7.0
4    12.0
dtype: float64
0         NaN
1         NaN
2    0.944911
3    0.970725
4    0.995402
dtype: float64


In [12]:
# 滑动窗口使用 apply 
import numpy as np 
import pandas as pd 

# 不适用 apply 函数
print(roller.mean())
print("=======================")
# 使用 apply 函数
print(roller.apply(lambda x:x.mean()))

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64


In [13]:
# 类滑窗函数 
import numpy as np 
import pandas as pd 

s = pd.Series([1,3,6,10,15])
print(s)
print("======================")
print(s.shift(2))  # shift 函数
print("======================")
print(s.diff(3))   # diff 函数
print("======================")
print(s.pct_change())  # pct_change 函数
print("======================")
print(s.shift(-1))
print("======================")
print(s.diff(-2))

0     1
1     3
2     6
3    10
4    15
dtype: int64
0    NaN
1    NaN
2    1.0
3    3.0
4    6.0
dtype: float64
0     NaN
1     NaN
2     NaN
3     9.0
4    12.0
dtype: float64
0         NaN
1    2.000000
2    1.000000
3    0.666667
4    0.500000
dtype: float64
0     3.0
1     6.0
2    10.0
3    15.0
4     NaN
dtype: float64
0   -5.0
1   -7.0
2   -9.0
3    NaN
4    NaN
dtype: float64


In [14]:
import numpy as np 
import pandas as pd 

s = pd.Series([1,3,6,10,15])
print(s)
print("======================")
print(s.rolling(3).apply(lambda x:list(x)[0]))  # s.shift(2)
print("======================")
print(s.rolling(4).apply(lambda x:list(x)[-1] - list(x)[0])) # s.diff(3)
print("======================")
def my_pct(x):
    L = list(x)
    return L[-1]/L[0] - 1

print(s.rolling(2).apply(my_pct)) # s.pct_change()

0     1
1     3
2     6
3    10
4    15
dtype: int64
0    NaN
1    NaN
2    1.0
3    3.0
4    6.0
dtype: float64
0     NaN
1     NaN
2     NaN
3     9.0
4    12.0
dtype: float64
0         NaN
1    2.000000
2    1.000000
3    0.666667
4    0.500000
dtype: float64


In [15]:
# 扩张窗口
import numpy as np 
import pandas as pd 

s = pd.Series([1,3,6,10])
print(s.expanding().mean())

0    1.000000
1    2.000000
2    3.333333
3    5.000000
dtype: float64


In [3]:
# 练习1 口袋妖怪数据集
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/Pokemon.csv')
print(df.head())

   #                   Name Type 1  Type 2  ...  Defense  Sp. Atk  Sp. Def  Speed
0  1              Bulbasaur  Grass  Poison  ...       49       65       65     45
1  2                Ivysaur  Grass  Poison  ...       63       80       80     60
2  3               Venusaur  Grass  Poison  ...       83      100      100     80
3  3  VenusaurMega Venusaur  Grass  Poison  ...      123      122      120     80
4  4             Charmander   Fire     NaN  ...       43       60       50     65

[5 rows x 11 columns]


In [8]:
# (1)
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/Pokemon.csv')

df[['HP','Attack','Defense','Sp. Atk','Sp. Def','Speed']].sum(axis = 1).head(10) == df['Total'].head(10)

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [22]:
# (2)
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/Pokemon.csv')

# 只保留第一条记录
df_unique = df.drop_duplicates(['#'],keep = 'first')
print(df_unique.head(5))
# a. 第一属性的种类数量
print(df_unique['Type 1'].nunique())
# a. 前三多数量对应的种类
print(df_unique['Type 1'].value_counts().index[:3])
# b. 第一属性和第二属性的组合种类
df_type_sum = df_unique.drop_duplicates(['Type 1','Type 2'])
# print(df_type_sum.sum()) # unhashable type: 'list'
print(df_type_sum.shape[0])
# c. 尚未出现过的属性组合
L_full = [i+' '+j for i in df['Type 1'].unique() for j in (df['Type 1'].unique().tolist() + [''])]
L_part = [i+' '+j for i, j in zip(df['Type 1'], df['Type 2'].replace(np.nan, ''))]
res = set(L_full).difference(set(L_part))
print(len(res))

   #        Name Type 1  Type 2  ...  Defense  Sp. Atk  Sp. Def  Speed
0  1   Bulbasaur  Grass  Poison  ...       49       65       65     45
1  2     Ivysaur  Grass  Poison  ...       63       80       80     60
2  3    Venusaur  Grass  Poison  ...       83      100      100     80
4  4  Charmander   Fire     NaN  ...       43       60       50     65
5  5  Charmeleon   Fire     NaN  ...       58       80       65     80

[5 rows x 11 columns]
18
Index(['Water', 'Normal', 'Grass'], dtype='object')
143
188


In [30]:
# (3)
import numpy as np 
import pandas as pd 

df = pd.read_csv('data/Pokemon.csv')

# a. 
#print(df.mask(df['Attack'] > 120,'high').mask(df['Attack'] < 50,'low').mask(df['Attack'] >= 50 and df['Attack'] <= 120,'mid')) #The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
#print(df['Attack'].mask(df['Attack'] > 120,'high').mask(df['Attack'] < 50,'low').mask(df['Attack'] >= 50 and df['Attack'] <= 120,'mid'))
print(df['Attack'].mask(df['Attack']>120, 'high').mask(df['Attack']<50, 'low').mask((50<=df['Attack'])&(df['Attack']<=120), 'mid').head())
print("================================")
# b.
print(df['Type 1'].replace({i:str.upper(i) for i in df['Type 1'].unique()}).head())
print(df['Type 1'].apply(lambda x:str.upper(x)).head())
print("================================")
# c.
df['Deviation'] = df[['HP', 'Attack', 'Defense', 'Sp. Atk','Sp. Def', 'Speed']].apply(lambda x:np.max((x-x.median()).abs()), 1)
print(df.sort_values('Deviation', ascending=False).head())

0    low
1    mid
2    mid
3    mid
4    mid
Name: Attack, dtype: object
0    GRASS
1    GRASS
2    GRASS
3    GRASS
4     FIRE
Name: Type 1, dtype: object
0    GRASS
1    GRASS
2    GRASS
3    GRASS
4     FIRE
Name: Type 1, dtype: object
       #                 Name  Type 1  ... Sp. Def  Speed  Deviation
230  213              Shuckle     Bug  ...     230      5      215.0
121  113              Chansey  Normal  ...     105     50      207.5
261  242              Blissey  Normal  ...     135     55      190.0
333  306    AggronMega Aggron   Steel  ...      80     50      155.0
224  208  SteelixMega Steelix   Steel  ...      95     30      145.0

[5 rows x 12 columns]


In [32]:
# 作为扩张窗口的 ewm 窗口
import numpy as np 
import pandas as pd

np.random.seed(0)
s = pd.Series(np.random.randint(-1,2,30).cumsum())
print(s.head())
print(s.ewm(alpha=0.2).mean().head())

0   -1
1   -1
2   -2
3   -2
4   -2
dtype: int32
0   -1.000000
1   -1.000000
2   -1.409836
3   -1.609756
4   -1.725845
dtype: float64


In [33]:
# 1. 
import numpy as np 
import pandas as pd 

np.random.seed(0)
s = pd.Series(np.random.randint(-1,2,30).cumsum())
print(s.ewm(alpha=0.2).mean().head())

def ewm_func(x, alpha=0.2):
    win = (1-alpha)**np.arange(x.shape[0])[::-1]
    res = (win*x).sum()/win.sum()
    return res

print(s.expanding().apply(ewm_func).head())

0   -1.000000
1   -1.000000
2   -1.409836
3   -1.609756
4   -1.725845
dtype: float64
0   -1.000000
1   -1.000000
2   -1.409836
3   -1.609756
4   -1.725845
dtype: float64


In [35]:
# 2. 
import numpy as np 
import pandas as pd 

np.random.seed(0)
s = pd.Series(np.random.randint(-1,2,30).cumsum())

def ewm_func(x, alpha=0.2):
    win = (1-alpha)**np.arange(x.shape[0])[::-1]
    res = (win*x).sum()/win.sum()
    return res

print(s.rolling(window=4).apply(ewm_func).head())

0         NaN
1         NaN
2         NaN
3   -1.609756
4   -1.826558
dtype: float64
