In [1]:
#python 基础

In [2]:
L = []

def my_function(x):
    return 2 * x

for i in range(5):
    L.append(my_function(i))
    
print(L)

[0, 2, 4, 6, 8]


In [3]:
def my_function(x):
    return 2 * x

L = [my_function(i) for i in range(5)]

print(L)


[0, 2, 4, 6, 8]


In [4]:
L = [m + '_' + n for m in ['a','b'] for n in ['c','d']]
# m 为第一层循环  n 为第二层循环
print(L)

['a_c', 'a_d', 'b_c', 'b_d']


In [5]:
value = 'cat' if 2 > 1 else 'dog'
print(value)

cat


In [6]:
#等价于下面的写法
a,b = 'cat','dog'
condition = 2 > 1 #此时为True
if condition:
    value = a
else:
    value = b
    
print(value)

cat


In [7]:
# 截断列表中超过5的元素
L = [1,2,3,4,5,6,7,8,9]

Ls = [i if i <= 5 else 5 for i in L]
print(Ls)

[1, 2, 3, 4, 5, 5, 5, 5, 5]


In [9]:
#匿名函数
my_function = lambda x : 2 * x
print(my_function(3))

multi_para_func = lambda a,b : a + b
print(multi_para_func(1,2))

6
3


In [10]:
L = [(lambda x : 2 * x)(i) for i in range(5)]
print(L)

[0, 2, 4, 6, 8]


In [11]:
L = list(map(lambda x : 2 * x,range(5)))
print(L)

[0, 2, 4, 6, 8]


In [12]:
L = list(map(lambda x,y : str(x) + '_' + y,range(5),list('abcde')))
print(L)

['0_a', '1_b', '2_c', '3_d', '4_e']


In [3]:
#zip
a = [1,2,3]
b = [4,5,6]
c = [4,5,6,7,8]
# 打包为元组的列表
zipped = zip(a,b)
print(zipped)
print(list(zipped))
# 元素个数与最短的列表一致
zipped02 = zip(a,c)
print(list(zipped02))

print(type(zipped))

#解压，返回二维矩阵式
print(list(*zip(zipped)))

[(1, 4), (2, 5), (3, 6)]
[(1, 4), (2, 5), (3, 6)]
<class 'zip'>
[]


In [23]:
zipped

In [4]:
m5=[1,2,3] 
n5=[4,5,6] 
k5=[7,8,9] 
zip5=zip(m5,n5,k5)

In [6]:
list(zip5)

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [8]:
list(zip(*zip5))

[]

In [9]:
m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 
n = [[2, 2, 2], [3, 3, 3], [4, 4, 4]]
 
print(“zip(m, n)返回:\n”, zip(m, n)) # 
print(“*zip(m, n)返回:\n”, *zip(m, n))

SyntaxError: invalid character in identifier (<ipython-input-9-648b04e74680>, line 4)

In [1]:
# 创建2个列表
m = [1, 2, 3]
n = [4, 5, 6]

print("*zip(m, n)返回:", *zip(m, n))
m2, n2 = zip(*zip(m, n))
print("m2和n2的值分别为:", m2, n2)
# 若相等，返回True；说明*zip为zip的逆过程
print(m == list(m2) and n == list(n2))

*zip(m, n)返回: (1, 4) (2, 5) (3, 6)
m2和n2的值分别为: (1, 2, 3) (4, 5, 6)
True


In [7]:
#zip
L1,L2,L3 = list('abc'),list('def'),list('hij')

print(list(zip(L1,L2,L3)))#list 形式
print(tuple(zip(L1,L2,L3)))#tuple 形式

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
(('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j'))


In [11]:
# 定义三个列表
a = [1,2,3]
b = [4,5,6]
c = [4,5,6,7,8,9]

a_b = zip(a,b)
print(list(a_b))
print(a_b)
print(list(a_b)) # 使用一次过后 a_b会被改变

# 以最短的保持一致
a_c = zip(a,c)
print(tuple(a_c))

[(1, 4), (2, 5), (3, 6)]
[]
((1, 4), (2, 5), (3, 6))


In [22]:
# 声明一个列表 
nums = [[1,2,3],[4,5,6]]
# 参数为一个列表
print(list(zip(*nums)))

a = [1,2,3]
b = [4,5,6]
# 参数为zip()函数返回的对象
zipped = zip(a,b)
print(list(zip(*zipped)))

[(1, 4), (2, 5), (3, 6)]
[(1, 2, 3), (4, 5, 6)]


In [32]:
# *zip()函数
# 声明两个列表
m = [1,2,3]
n = [4,5,6]

zipped = zip(a,b)
print(list(zipped))
print(list(zip(*zip(a,b)))) # zip()与*zip() 互为逆过程

[(1, 4), (2, 5), (3, 6)]
[(1, 2, 3), (4, 5, 6)]


In [34]:
L1,L2,L3 = list('abc'),list('def'),list('hij')
for i,j,k in zip(L1,L2,L3):
    print(i,j,k)

a d h
b e i
c f j


In [35]:
L = list('abcd')
for index,value in enumerate(L):
    print(index,value)

0 a
1 b
2 c
3 d


In [37]:
# zip()也可以实现enumerate 的功能
nbaPlayersName = ['勒布朗','杜兰特','库里','小卡','字母哥']
print("我心中的现役前五：")
for num,name in zip(range(len(nbaPlayersName)),nbaPlayersName):
    print(num + 1,name)

我心中的现役前五：
1 勒布朗
2 杜兰特
3 库里
4 小卡
5 字母哥


In [38]:
books = ['你的孤独，虽败犹荣','我在等风，也等你','乖，摸摸头']
authors = ['刘同','何小然','大冰']
print(dict(zip(books,authors))) # 字典形式

{'你的孤独，虽败犹荣': '刘同', '我在等风，也等你': '何小然', '乖，摸摸头': '大冰'}


In [40]:
L1,L2,L3 = list('abc'),list('def'),list('hij')

print(list(zip(L1,L2,L3)))
print(list(zip(*zip(L1,L2,L3)))) # 三个元组分别对应原来的列表

[('a', 'd', 'h'), ('b', 'e', 'i'), ('c', 'f', 'j')]
[('a', 'b', 'c'), ('d', 'e', 'f'), ('h', 'i', 'j')]


In [1]:
# numpy基础

In [3]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 等差序列
import numpy as np 

arr01 = np.linspace(1,5,11) # 起始、终止(包含)、样本个数     等分
print(arr01)

arr02 = np.arange(1,5,2) # 起始、终止(不包含)、步长
print(arr02)

[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]
[1 3]


In [8]:
# 特殊矩阵
import numpy as np 

arr_zero = np.zeros((3,3)) # 零矩阵  (3,3)表示矩阵各维度的大小
print(arr_zero)

arr_eye = np.eye(3) # 3*3 的单位矩阵
print(arr_eye)

arr_eye_flase = np.eye(3,k = 1) # 偏移主对角线1个单位的伪单位矩阵
print(arr_eye_flase)

arr_full = np.full((2,3),10) # 元组传入大小，10 表示填充数值
print(arr_full)

arr_full_a = np.full((2,3),[1,2,3]) # 通过传入列表填充每列的值
print(arr_full_a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[10 10 10]
 [10 10 10]]
[[1 2 3]
 [1 2 3]]


In [9]:
# 随机矩阵01
'''

最常用的随机生成函数为 
    rand     :  0-1均匀分布的随机数组
    randn    :  标准正态的随机数组
    randint  :  随机整数组
    choice   :  随机列表抽样
    
'''

import numpy as np 

arr01 = np.random.rand(3) # 生成服从0-1均匀分布的三个随机数
print(arr01)

arr02 = np.random.rand(3,3) # 注意这里传入的不是元组，每个维度大小分开输入
print(arr02)

# 对于服从区间a到b上的均匀分布可以如下生成
a,b = 5,15
arr03 = (b - a) * np.random.rand(2,2) + a
print(arr03)

# randn 生成了 N(0,1) 的标准正态分布
arr04 = np.random.randn(3)
print(arr04)

arr05 = np.random.randn(2,2)
print(arr05)

# 对于服从方差为 σ2 ,均值为 μ 的一元正态分布可以如下生成
sigma,mu = 2.5,3
arr06 = mu + np.random.randn(2,2) * sigma
print(arr06)



[0.38315324 0.12044393 0.58867398]
[[0.55663665 0.32474479 0.79753092]
 [0.19868349 0.87332289 0.21547287]
 [0.17919124 0.68943672 0.75621964]]
[[ 6.57864932 11.69826487]
 [13.73869486  9.12119517]]
[-0.38387813  1.29116147  1.864059  ]
[[ 0.21267433 -0.03010171]
 [ 1.39688789 -0.57474523]]
[[2.42115033 2.59893279]
 [3.829758   5.2627406 ]]


In [11]:
# 随机矩阵02

import numpy as np 

# randint 可以指定生成随机整数的最小值最大值（不包含）和维度大小
low,high,size = 5,15,(2,2)
arr01 = np.random.randint(low,high,size)
print(arr01)

# choice 可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样
my_list = ['a','b','c','d']
arr_choice01 = np.random.choice(my_list,2,replace = False,p = [0.1,0.7,0.1,0.1])
print(arr_choice01)

arr_choice02 = np.random.choice(my_list,(2,2))
print(arr_choice02)

# 当返回的元素个数与原列表相同时，等价于使用 permutation 函数，即打散原列表
arr_permutation = np.random.permutation(my_list)
print(arr_permutation)

# 需要提到的是随机种子，它能够固定随机数的输出结果
np.random.seed(20201215)
arr_seed01 = np.random.rand()
print(arr_seed01)
np.random.seed(20201215)
arr_seed02 = np.random.rand()
print(arr_seed02)

[[ 6 14]
 [12  8]]
['b' 'd']
[['d' 'a']
 ['a' 'd']]
['d' 'b' 'a' 'c']
0.4102719865683089
0.4102719865683089


In [12]:
# 转置
import numpy as np 

arr01 = np.zeros((2,3))
print(arr01)
arr02 = arr01.T
print(arr02)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [15]:
# 合并操作
import numpy as np

arr01 = np.zeros((2,3))
print(arr01)
arr_r = np.r_[arr01,arr01] # 注意 r_、c_符号用 []
print(arr_r)
arr_c = np.c_[arr01,arr01]
print(arr_c)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [16]:
# 一维数组与二维数组进行合并
import numpy as np 

try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    Err_Msg = e
print(Err_Msg)

arr01 = np.r_[np.array([0,0]),np.zeros(2)]
print(arr01)

# 一维与二维，左右合并
arr02 = np.c_[np.array([0,0]),np.zeros((2,3))]
print(arr02)


all the input arrays must have same number of dimensions
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
# 维度变换  reshape
import numpy as np 

target = np.arange(8).reshape(2,4)
print(target)

arr01 = target.reshape((4,2),order = 'C') #  按照行读取和填充
print(arr01)

arr02 = target.reshape((4,2),order = 'F') #  按照列读取和填充
print(arr02)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [18]:
import numpy as np 

target = np.arange(8).reshape(2,4)
print(target)

arr01 = target.reshape((4,-1))
print(arr01)


[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [19]:
import numpy as np 

target = np.ones((3,1))
print(target)

arr01 = target.reshape(-1) # -1 转换为1维数组
print(arr01)
arr02 = target.T # 转置
print(arr02)    # 注意 有所不同


[[1.]
 [1.]
 [1.]]
[1. 1. 1.]
[[1. 1. 1.]]


In [1]:
# 切片和索引
import numpy as np 

target = np.arange(9).reshape(3,3)
print(target)
# 切片
print(target[:-1,[0,2]]) # end(不包含), [0,2]表示第1列和第3列

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2]
 [3 5]]


In [2]:
# np.ix_切片索引
import numpy as np 

target = np.arange(9).reshape(3,3)
print(target)

print(target[np.ix_([True,False,True],[True,False,True])]) # 切片

print(target[np.ix_([1,2],[True,False,True])]) # 组合切片 np.ix_和维度

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2]
 [6 8]]
[[3 5]
 [6 8]]


In [3]:
# 一维索引
import numpy as np 

target = np.arange(9).reshape(3,3)
print(target)

new_target = target.reshape(-1) # 转换为一维数组
print(new_target)
print(new_target[new_target % 2 == 0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]


In [5]:
# where函数
import numpy as np 

a = np.array([-1,1,-1,0])
print(a)

b = np.where(a > 0,a,5) # 类似于 ? 表达式（可惜python中没有）
print(b)

[-1  1 -1  0]
[5 1 5 5]


In [9]:
# nonzero , argmax , argmin 函数
import numpy as np 

a = np.array([-2,-5,0,1,3,-1])
print(a)
print(np.nonzero(a)) # 非零索引
print(np.argmax(a)) # 最大值索引
print(np.argmin(a)) # 最小值索引

# 还可以如下
print("============")
print(a.nonzero())
print(a.argmax())
print(a.argmin())

[-2 -5  0  1  3 -1]
(array([0, 1, 3, 4, 5], dtype=int64),)
4
1
(array([0, 1, 3, 4, 5], dtype=int64),)
4
1


In [12]:
# any , all
import numpy as np 

a = np.array([0,1])
print(a)
print(a.any())
print(a.all())
print("===============")
print(np.any(a))
print(np.all(a))


[0 1]
True
False
True
False


In [2]:
# cumprod , cumsum , diff
import numpy as np 

a = np.array([1,2,3])
print(a)

print(a.cumprod())
print(a.cumsum())
print(np.diff(a)) # a.diff() 出错  'numpy.ndarray' object has no attribute  'diff'


[1 2 3]
[1 2 6]
[1 3 6]
[1 1]


In [3]:
# 统计函数
import numpy as np 

target = np.arange(5)
print(target)

print(target.max()) # 最大值
print(np.quantile(a,0.5)) # 0.5分位数

[0 1 2 3 4]
4
2.0


In [6]:
# nan*
import numpy as np 

target = np.array([1,2,np.nan])
print(target)

print(target.max())
print(np.nanmax(target))
print(np.nanquantile(target,0.5))

[ 1.  2. nan]
nan
2.0
1.5


In [7]:
# 协方差和相关系数
import numpy as np 

target1 = np.array([1,3,5,9])
print(target1)
target2 = np.array([1,5,3,-9])
print(target2)

print(np.cov(target1,target2)) # 协方差
print(np.corrcoef(target1,target2)) # 相关系数

[1 3 5 9]
[ 1  5  3 -9]
[[ 11.66666667 -16.66666667]
 [-16.66666667  38.66666667]]
[[ 1.         -0.78470603]
 [-0.78470603  1.        ]]


In [8]:
# 维度参数 axis
import numpy as np 

target = np.arange(1,10).reshape(3,-1)
print(target)

# axis = 0 
print(target.sum(0))
# axis = 1
print(target.sum(1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [11]:
# 广播机制 标量和数组操作
import numpy as np 

one = np.ones((2,2))
print(one)

res = 3 * one + 1
print(res)

ress = 1 / res
print(ress)

[[1. 1.]
 [1. 1.]]
[[4. 4.]
 [4. 4.]]
[[0.25 0.25]
 [0.25 0.25]]


In [15]:
# 广播机制 二维数组之间操作
import numpy as np 

res1 = np.array([2,3])
print(res1)
res2 = np.ones((3,2))
print(res2)
res3 = np.array([[2],[3],[4]])
print(res3)
res4 = np.array([2])
print(res4)

print("====================")

result1 = res1 * res2 # res1扩充第一维度为3
print(result1)
result2 = res2 * res3 # res3扩充第二维度为2
print(result2)
result3 = res2 * res4 # res4扩充两次
print(result3)

[2 3]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2]
 [3]
 [4]]
[2]
[[2. 3.]
 [2. 3.]
 [2. 3.]]
[[2. 2.]
 [3. 3.]
 [4. 4.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [19]:
# 广播机制 一维数组与二维数组的操作
import numpy as np 

res1 = np.ones(3)
print(res1)
res2 = np.ones((2,3))
print(res2)
res3 = np.ones((2,1))
print(res3)
res4 = np.ones(1)
print(res4)
print("=================")
result1 = res1 + res2
print(result1)
result2 = res1 + res3
print(result2)
result3 = res4 + res2
print(result3)

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.]
 [1.]]
[1.]
[[2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]]
[[2. 2. 2.]
 [2. 2. 2.]]


In [20]:
# 向量内积
import numpy as np 

a = np.array([1,2,3])
print(a)
b = np.array([1,3,5])
print(b)

result = a.dot(b)
print(result)

[1 2 3]
[1 3 5]
22


In [23]:
# 范数
import numpy as np 

martix_target = np.arange(4).reshape(-1,2)
print(martix_target)
print(np.linalg.norm(martix_target,'fro'))
print(np.linalg.norm(martix_target,np.inf))
print(np.linalg.norm(martix_target,2))

print("=====================")

vector_target = np.arange(4)
print(vector_target)
print(np.linalg.norm(vector_target,np.inf))
print(np.linalg.norm(vector_target,2))
print(np.linalg.norm(vector_target,3))

[[0 1]
 [2 3]]
3.7416573867739413
5.0
3.702459173643833
[0 1 2 3]
3.0
3.7416573867739413
3.3019272488946263


In [24]:
# 矩阵乘法
import numpy as np 

a = np.arange(4).reshape(-1,2)
print(a)
b = np.arange(-4,0).reshape(-1,2)
print(b)
result = a @ b 
print(result)

[[0 1]
 [2 3]]
[[-4 -3]
 [-2 -1]]
[[ -2  -1]
 [-14  -9]]


In [30]:
# 练习 1  三重循环
import numpy as np 

M1 = np.random.rand(2,3)
print(M1)
M2 = np.random.rand(3,4)
print(M2)
res = np.empty((M1.shape[0],M2.shape[1]))
print(res)

# 矩阵乘法
for i in range(M1.shape[0]):
    for j in range(M2.shape[1]):
        item = 0
        for k in range(M1.shape[1]):
            item += M1[i][k] * M2[k][j]
        res[i][j] = item

print(((M1 @ M2 - res) < 1e-15).all())  # 排除数值误差

[[0.99337527 0.36524304 0.85329933]
 [0.45951714 0.80551173 0.30855875]]
[[0.81295248 0.96892189 0.49708572 0.90129861]
 [0.85357571 0.5645595  0.51336681 0.73962945]
 [0.09469644 0.0047622  0.16766094 0.23720669]]
[[3.5 1.5 0.5 4.5]
 [1.  5.  3.  9. ]]
True


In [41]:
# numpy.empty
import numpy as np 

a = np.empty((2,2))
print(a)
b = np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


In [42]:
# numpy.shape
import numpy as np 

x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]],[[3,4,5],[6,7,8]]])
print(x)

print("==================")
print(x.shape)
print(x.shape[0])
print(x.shape[1])
print(x.shape[2])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]

 [[3 4 5]
  [6 7 8]]]
(3, 2, 3)
3
2
3


In [54]:
# 列表推导式写矩阵乘法
import numpy as np 

M1 = np.random.rand(2,3)
print(M1)
M2 = np.random.rand(3,4)
print(M2)

res = np.empty((M1.shape[0],M2.shape[1]))
print(res)

res = [[sum([M1[i][k] * M2[k][j] for k in range(M1.shape[1])]) for j in range(M2.shape[1])] for i in range(M1.shape[0])]

print(((M1 @ M2 - res) < 1e-15).all())


[[0.74403318 0.3472746  0.86100323]
 [0.27047585 0.95432698 0.75657926]]
[[0.61937321 0.70487147 0.97848333 0.534197  ]
 [0.1272389  0.75809047 0.75214979 0.40443144]
 [0.26317261 0.86496878 0.46693493 0.08052959]]
[[1.49503606 0.67283691 0.72008662 1.22812569]
 [0.60608374 0.21715434 0.34631747 0.59446545]]
True


In [46]:
x = [str(i) + str(j) for i in [4,5,6] for j in [1,2,3] ]

In [47]:
x

['41', '42', '43', '51', '52', '53', '61', '62', '63']

In [45]:
for i in [1,2,3]:
    for j in [4,5,6]:
        print(str(i) + str(j))

14
15
16
24
25
26
34
35
36


In [59]:
# 更新矩阵 普通方法
import numpy as np 

A = np.arange(1,10).reshape((3,-1))
print(A)
B = np.empty(A.shape)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        item = 0
        for k in range(A.shape[1]):
            item += 1/A[i][k]
        B[i][j] = A[i][j] * item 
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.83333333 3.66666667 5.5       ]
 [2.46666667 3.08333333 3.7       ]
 [2.65277778 3.03174603 3.41071429]]


In [60]:
# 更新矩阵 numpy高效
import numpy as np 

A = np.arange(1,10).reshape((3,-1))
print(A)
B = A * (1/A).sum(1).reshape(-1,1)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1.83333333 3.66666667 5.5       ]
 [2.46666667 3.08333333 3.7       ]
 [2.65277778 3.03174603 3.41071429]]


In [61]:
print(1/A)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


In [62]:
print(A.sum(1))

[ 6 15 24]


In [63]:
# 卡方统计量
import numpy as np 

# 设置随机数种子
np.random.seed(0)
A = np.random.randint(10,20,(8,5))
print(A)
B = A.sum(0) * A.sum(1).reshape(-1,1) / A.sum()
print(B)
res = ((A - B) ** 2 / B).sum()
print(res)

[[15 10 13 13 17]
 [19 13 15 12 14]
 [17 16 18 18 11]
 [16 17 17 18 11]
 [15 19 18 19 14]
 [13 10 13 15 10]
 [12 13 18 11 13]
 [13 13 17 10 11]]
[[14.14211438 13.08145581 15.20277296 13.67071057 11.90294627]
 [15.18197574 14.04332756 16.32062392 14.67590988 12.77816291]
 [16.63778163 15.38994801 17.88561525 16.08318891 14.0034662 ]
 [16.42980936 15.19757366 17.66204506 15.88214905 13.82842288]
 [17.67764298 16.35181976 19.0034662  17.08838821 14.87868284]
 [12.68630849 11.73483536 13.63778163 12.26343154 10.67764298]
 [13.93414211 12.88908146 14.97920277 13.46967071 11.72790295]
 [13.3102253  12.31195841 14.3084922  12.86655113 11.20277296]]
11.842696601945802


In [65]:
# 改进矩阵的性能
import numpy as np 

np.random.seed(0)
m,n,p = 100,80,50

B = np.random.randint(0,2,(m,p))
print(B)
U = np.random.randint(0,2,(p,n))
print(U)
Z = np.random.randint(0,2,(m,n))
print(Z)
print("==================")

def solution(B = B,U = U,Z = Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i] - U[:,j]) ** 2).sum()
            L_res.append(norm_value * Z[i][j])
    return sum(L_res)

print(solution(B,U,Z))

[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
[[1 0 1 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 1 1]
 ...
 [1 0 1 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 1]]
[[1 0 0 ... 1 0 0]
 [0 1 1 ... 1 1 0]
 [1 0 1 ... 0 1 1]
 ...
 [0 1 0 ... 1 1 0]
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]]
100566


In [66]:
# 改进方法
import numpy as np 

np.random.seed(0)
m,n,p = 100,80,50

B = np.random.randint(0,2,(m,p))
print(B)
U = np.random.randint(0,2,(p,n))
print(U)
Z = np.random.randint(0,2,(m,n))
print(Z)
print("==================")

print((((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2*B@U)*Z).sum())

[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 1 1 1]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
[[1 0 1 ... 1 1 0]
 [0 0 0 ... 0 0 1]
 [0 1 0 ... 0 1 1]
 ...
 [1 0 1 ... 1 0 1]
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 1]]
[[1 0 0 ... 1 0 0]
 [0 1 1 ... 1 1 0]
 [1 0 1 ... 0 1 1]
 ...
 [0 1 0 ... 1 1 0]
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 1]]
100566


In [68]:
# 对比性能
%timeit -n 30 solution(B, U, Z)

45.7 ms ± 1.96 ms per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [69]:
%timeit -n 30 ((np.ones((m,n))*(B**2).sum(1).reshape(-1,1) +\
              np.ones((m,n))*(U**2).sum(0) - 2*B@U)*Z).sum()

688 µs ± 78.3 µs per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [70]:
# 求连续整数的最大长度 参考答案真牛皮 自己还差很多点😂
import numpy as np 

f = lambda x:np.diff(np.nonzero(np.r_[1,np.diff(x)!=1,1])).max()
print(f([1,2,5,6,7]))
print(f([3,2,1,2,3,4,6]))

3
4
